name: Bump Version

on:
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bump version
        uses: anothrNick/github-tag-action@v1.17.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.VERSION }}
          tag_message: ${{ env.VERSION }}
          release_branches: main
          major_minor_or_patch: ${{ env.BUMP_TYPE }}
          commit_sha: ${{ env.COMMIT_SHA }}
