name: Bump Version

on:
  workflow_dispatch:
    inputs:
      commit_sha: 
        description: 'Enter the commit SHA'
        type: string
        required: false
      version_fragment: 
        description: 'Choose the bump type'
        required: true
        default: 'bug'
        options: ['major', 'feature', 'bug', 'alpha', 'beta', 'pre', 'rc']
        type: choice

jobs:
  bump-version:
    runs-on: ubuntu-22.04
    if: ${{ github.ref_name }} == ${{ github.event.repository.default_branch }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          
      - name: Get Previous tag
        id: previous_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1.3.0"
        with:
          # Optional fallback tag to use when no tag can be found
          fallback: 0.0.0
          prefix: v
          
      - name: Bump version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.1.0
        with:
          current-version: ${{ steps.previous_tag.outputs.tag }}
          version-fragment: ${{ github.event.inputs.version_fragment }}
          
      - name: "New Version: ${{ steps.bump_version.outputs.next-version }}"
        run: ":"
        
      - name: Push tag
        id: push_tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        # commit_sha: ${{ github.event.inputs.commit_sha }}
          custom_tag: ${{ steps.bump_version.outputs.next-version }}

    # - name: Bump version and set tag at current commit
    #   uses: anothrNick/github-tag-action@v1.61.0
    #   with:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     WITH_V: true
    #     RELEASE_BRANCHES: ${{ github.event.repository.default_branch }}
    #     major_minor_or_patch: ${{ github.event.inputs.bump_type }}
    #     commit_sha: ${{ env.COMMIT_SHA }}
